# Auto-generated movie data
movies = [
    {'title': 'Planet of the apes', 'clean_title': 'Planet of the apes', 'code': 'M001', 'gp_link': 'https://gplinks.co/Ud8iini', 'backup_link': 'https://pubnotepad.com/a2BXmO', 'poster': 'posters/Planet_of_the_apes.jpg', 'description': 'Astronaut Taylor crash lands on a distant planet ruled by apes who use a primitive race of humans for experimentation and sport. Soon Taylor finds himself among the hunted, his life in the hands of a benevolent chimpanzee scientist.', 'type': 'movie', 'genre': 'Science Fiction, Adventure, Drama, Action'},
    {'title': 'The green Knight', 'clean_title': 'The green Knight', 'code': 'M005', 'gp_link': 'https://gplinks.co/mvMXPyq', 'backup_link': 'https://pubnotepad.com/J36hxb', 'poster': 'posters/The_green_Knight.jpg', 'description': "An epic fantasy adventure based on the timeless Arthurian legend, The Green Knight tells the story of Sir Gawain, King Arthur's reckless and headstrong nephew, who embarks on a daring quest to confront the eponymous Green Knight, a gigantic emerald-skinned stranger and tester of men.", 'type': 'movie', 'genre': 'Adventure, Drama, Fantasy'},
    {'title': 'Captain.America.Brave.New.World.(2025).', 'clean_title': 'Captain America Brave New World', 'code': 'M006', 'gp_link': 'https://gplinks.co/V91mH', 'backup_link': 'https://pubnotepad.com/19TNbQ', 'poster': 'posters/Captain_America_Brave_New_World.jpg', 'description': 'After meeting with newly elected U.S. President Thaddeus Ross, Sam finds himself in the middle of an international incident. He must discover the reason behind a nefarious global plot before the true mastermind has the entire world seeing red.', 'type': 'movie', 'genre': 'Action, Thriller, Science Fiction'},
    {'title': 'the killers game', 'clean_title': 'the killers game', 'code': 'M010', 'gp_link': 'https://gplinks.co/Kbmy', 'backup_link': 'https://pubnotepad.com/vUpULi', 'poster': 'posters/the_killers_game.jpg', 'description': "When top hitman Joe Flood is diagnosed with a terminal illness, he decides to take matters into his own hands – by taking a hit out on himself. But when the very hitmen he hired also target his ex-girlfriend, he must fend off an army of assassin colleagues and win back the love of his life before it's too late.", 'type': 'movie', 'genre': 'Action, Comedy, Thriller'},
    {'title': 'Sugar.Baby.(2024) [18+]', 'clean_title': 'Sugar Baby', 'code': 'M011', 'gp_link': 'https://gplinks.co/9iKfeM', 'backup_link': 'https://pubnotepad.com/jKmmTj', 'poster': 'posters/Sugar_Baby.jpg', 'description': 'Love comes without asking. Often not to those, not so and not then. Can a genuine feeling survive when everything started wrong and the whole world is against it? Give up everything or give up? Burn or survive?', 'type': 'movie', 'genre': 'Romance, Drama'},
    {'title': 'Your.Fault.(2024) [18+]', 'clean_title': 'Your Fault', 'code': 'M012', 'gp_link': 'https://gplinks.co/wuEbvWS', 'backup_link': 'https://pubnotepad.com/HctHtB', 'poster': 'posters/Your_Fault.jpg', 'description': "The love between Noah and Nick seems unwavering despite their parents' attempts to separate them. But his job and her entry into college open up their lives to new relationships that will shake the foundations of both their relationship and the Leister family itself.", 'type': 'movie', 'genre': 'Romance, Drama'},
    {'title': 'Parallel.2024', 'clean_title': 'Parallel 2024', 'code': 'M014', 'gp_link': 'https://gplinks.co/mOoTM', 'backup_link': 'https://pubnotepad.com/kLd15X', 'poster': 'posters/Parallel_2024.jpg', 'description': 'aespa’s second worldwide tour encore concert live-streamed via Beyond LIVE and Weverse on March 16th, 2025.', 'type': 'movie', 'genre': 'Music'},
    {'title': 'The Conjuring 2013', 'clean_title': 'The Conjuring 2013', 'code': 'M023', 'gp_link': 'https://gplinks.co/RiMGtaaJ', 'backup_link': 'https://pubnotepad.com/GSOajg', 'poster': None, 'description': '', 'type': 'movie', 'genre': ''},
    {'title': 'Last.Breath.(2025)', 'clean_title': 'Last Breath', 'code': 'M027', 'gp_link': 'https://gplinks.co/zFi5l7AL', 'backup_link': 'https://pubnotepad.com/55R49O', 'poster': 'posters/Last_Breath.jpg', 'description': "Seasoned deep-sea divers battle the raging elements to rescue their crewmate trapped hundreds of feet below the ocean's surface.", 'type': 'movie', 'genre': 'Drama, Thriller'},
    {'title': 'Captain.America.Brave.New.World.(2025)', 'clean_title': 'Captain America Brave New World', 'code': 'M028', 'gp_link': 'https://gplinks.co/V91mH', 'backup_link': 'https://pubnotepad.com/19TNbQ', 'poster': 'posters/Captain_America_Brave_New_World.jpg', 'description': 'After meeting with newly elected U.S. President Thaddeus Ross, Sam finds himself in the middle of an international incident. He must discover the reason behind a nefarious global plot before the true mastermind has the entire world seeing red.', 'type': 'movie', 'genre': 'Action, Thriller, Science Fiction'},
    {'title': 'Love.2015', 'clean_title': 'Love 2015', 'code': 'M029', 'gp_link': 'https://gplinks.co/lznJeK', 'backup_link': 'https://pubnotepad.com/uFiRX7', 'poster': 'posters/Love_2015.jpg', 'description': 'Reward yourself or give a gift to your loved ones around you.', 'type': 'movie', 'genre': 'Animation'},
    {'title': 'Thunderbolts.(2025)', 'clean_title': 'Thunderbolts', 'code': 'M030', 'gp_link': 'https://gplinks.co/lOQG', 'backup_link': 'https://pubnotepad.com/E3pkBB', 'poster': 'posters/Thunderbolts.jpg', 'description': 'After finding themselves ensnared in a death trap, seven disillusioned castoffs must embark on a dangerous mission that will force them to confront the darkest corners of their pasts.', 'type': 'movie', 'genre': 'Action, Science Fiction, Adventure'},
    {'title': 'Matrix.1.The.Matrix.(1999)', 'clean_title': 'Matrix 1 The Matrix', 'code': 'M031', 'gp_link': 'https://gplinks.co/7wsPd', 'backup_link': 'https://pubnotepad.com/sZw4jJ', 'poster': 'posters/Matrix_1_The_Matrix.jpg', 'description': 'Set in the 22nd century, The Matrix tells the story of a computer hacker who joins a group of underground insurgents fighting the vast and powerful computers who now rule the earth.', 'type': 'movie', 'genre': 'Action, Science Fiction'},
]
